### PR TITLE
Source Codee for Feed page

### PR DESCRIPTION
**Pull request by weirdrag08**
Added Files:
Images/FeedPage/
Images/network.jpg
Images/redo.png
Images/undraw_buffer_wq43.svg
Layouts/FeedPage.html
Scripts/scroll-animation.js
Styles/feed.css

Modified Files:
Layouts/TeamPage.html
Styles/media-queries.css
index.html

<br>
<br>

1) 3 Column Layout (Min Width : 992px) (1368 X 768)=>
Three_col_layout

<br>
<br>

2) Hover Effect =>
Hover_effect

<br>
<br>

3) Fading Effect (while scrolling)=>
Fading_effect

<br>
<br>

4) 2 column Layout (Min Width: 575px) (843 X 768)=>
Two_col_layout

<br>
<br>

5) 1 Column Layout (414 X 736) =>
One_col_layout

### CODE REVIEW

**Comment by weirdrag08** [comment]
@saumyasingh203 Kindly review the PR.

**Review by saumyasingh203 — APPROVED** [review]
Great job, looks perfect!

**Comment by weirdrag08** [comment]
> Great job, looks perfect!

Thanks @saumyasingh203 . 
Also could you please tell me if we can create our own issues now to make certain additions and add more features to the existing site?

**Comment by saumyasingh203** [comment]
> > Great job, looks perfect!
> 
> Thanks @saumyasingh203 .
> Also could you please tell me if we can create our own issues now to make certain additions and add more features to the existing site?

Yes of course that'd be great! You guys can also add each other too as reviewers apart from me and merge the PR yourself, you'll get some insight about being a maintainer plus the code will be reviewed regularly. 
I'll be busy with my intern from now on so I think ^this will work out for the best 💯 Ping me if you across any problems.

**Pull request merged**
